language: python
python:
  - "3.7"
  - "3.8"
addons:
  chrome: stable
#make chrome run headless
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: python3 Main.py
#do before script
before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d