sudo: required
language: python
python:
- '3.7'
- '3.8'
addons:
  chrome: stable
#make chrome run headless
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- cd $TRAVIS_BUILD_DIR && ls -a && sudo chmod +x ecr_credential.sh && ls -a && ./ecr_credential.sh
install:
  - pip install -r requirements.txt
# command to run tests
script: python3 Main.py
#do before script
before_script:
- LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
- curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  -O
- unzip chromedriver_linux64.zip -d ~/bin
env:
  global:
  - secure: nzIgTnqc8A6PpNENfB0qhGfFzfnP1Em4k3bddEinw3y9aWhI7N73J2dSnNN/9A8IpMPpxd75hFJwV1PBW74F1OjWQQKqo27EIW7OkElgUy4z8mwalaJ9hOotjF8ucsLpOFCW6RkqSTAUAyqDRhQBhwjWNY0TcSLWwmsVSEwJHx582+WI7MvSkaQ8ALcw2Cpkg1/CvCb0xwWUiQO9sixvIF5qpyILP2eedSqxFa0DAOtzXPZmfEllh+8hvj+Rrn4eldSjyaKERzAmM0kpwN2r1WCXqjO9ZUDN+vNgUKr7KpvgYlE5jOyPTgaCAM4nqhouSBREwA+VPwlce4LwaAGzPZbpxImTjUmnGqJRvk/Zxu5N7TlnAwOu3IjN2H2MvNJijt/yy/YvhfdNP3jmCeGRhZb0dcdYpCnqcm+EghqFtw14dUWhX6vnkwPNiiQfC/OVUxcpQq+ZAQulUU46h2OHM5cVg+YYQnsuMlV6swPUkRDWSYy8JVGopRe5IP7JgncQnvMgEjFfw4l/W2wME6tHndj71etwStocj8tRBNDRRjUpKAFW0bVmwazqii2ztWUhltZM4Z0Ey4usjeN+uJOm88lBnz7eAlKW4mXN+irXqcQ2MMNJNw2Sy9zpckdaXsaiwYuInuArcRbw0E3hEL4+UrqLlIl4DBJkVmR0aY0jgdU=
  - secure: SrVq8xr5axvdpndakabpi/Y1VUzzonjawo3ttXXN8CkKhMX73QvMzHl5mpO7fe805Vn5k55CD5T/hcBDaJ7MU9tNfdvM8fPsY9TgqVQ2NO9cEdYaj+kgHzyo0txKD+ynb9W+qpZ1roDjsCHRaYHoSTSVB/HGKWbQxUVU2hNGiPOARtLLDaMeZBns2zyh6z/HVrkCmRIPJavuHCsxUuMNzYYdrS3WLjUQmksus9IgD2nEbGy+zgNnepsgEZ/wj48w/YLEqAhzaYSN9G3BXV8gNCRtoaSatPT/VhCZ8JYvGDJuBcGGzOFIj4D1jeEWD2gehSsRd8aQ5WeazrCEhRnBj6NyfeFFCM8scZW/xEtEYf3gc2n2QlccMAPxkMZUbsXotdVaaCe9NO6ime1fFbLQyRmaZ7b2fU/SEMh/d3oo8g6nnTM2F3gCmkk1Zk+fX3D/IIsRNzUuPcXXI7deB5FihgCwUp/bHNAeq5X8+0Ch5w+RYj+sDv/cv1JJEXryhF3feNHXZEeZtR2/eoxowoaNVmKSfn+u67BvGieeL/XAVEzmK0P/1RM3JJdo8SaJElxYoiTHa4wbn6/6bA0tQy4l1bHtjpR8kY7YiA+blC6qBppj+gxL1rOpd+6Xv07Qsih6+539rq0+QsxUFwSrmc+Q9Mmx4Cg39PV91j8SaomYG14=
