sudo: required
language: python
python:
- '3.7'
- '3.8'
addons:
  chrome: stable
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- cd $TRAVIS_BUILD_DIR && ls -a && sudo chmod +x ecr_credential.sh && ls -a && ./ecr_credential.sh
- aws configure list
install:
- pip install -r requirements.txt
script: python3 Main.py
before_script:
- LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
- curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  -O
- unzip chromedriver_linux64.zip -d ~/bin
env:
  global:
  - secure: ArsFsVs5ay+TVu6N0wSpzKm7fzDKiRZUdlTaGvHRMJG79YEZy0+0ln8ZxlXzfzU9oAu805Uq+Xl7XhORMrU9r5vIVtq/C95ebb80AgoE66DyhDsa3j9Y8zzAy5zIfUF3AioFY5wUgDMecOoblAwecZfbtTirSTIyPFu1TfLqBzpaGNhEsZFn8OkxC+Xdq9PJPnAnZCC5OdXoeeRCHnM1U51DlvdJYWuSyNwWuT2rGBJQlE5kq2BgIfSxmlSMtVD7rSwloKx4LdrmZ4QDNmjyONFWP3OkZ9AfIZRUEw+PHhISUgsmIVqRnbI2HGGzmN/82xpw9GRTygj9M74n7v8+cganXn3dg4sA7HM08Fc+2M8Qsv1xCt1f3ZF6mG9FmuBvfGuyI4gK6Go9NqrIinsA+8axpn3y5NTS8oiTCpkBZl+kVKFe4zuhaCGHRZdF5Yx5u7NWAvNS5pT8T460YqH3gLlVHYUmZfnxSktyl966Cqe/aQvMPTBpeKxFPxW8pC1QLbgXeHtHEjQfcmJbFbnnjvudS/xDl/SAIjJ3CXFydzX0fW7Me3TytFjJyi+Iw1YXFUnd4nwTYf+IFaxaKTJ102Ca8E0z+Bbz3u6FwFugy2U8LbXbpD3aoqK29q8JFzQrM6pWid7ipq2E/PKkuVRRXoDCj+tBNyrDogOAI0fEEr0=
  - secure: 2QTQLVCaFHT2eagjW2bJ25f5IxinR/4IcNsvsgR+a/k0lpivYsCHWpcTjZYxzdBOxLlAw5iZbgasorJ3sQWteTN3aJeVCc+DNhiWuGWuJ4+pAvsUFn9WiSXMCU9LazBhx/pnaSh16CEDzuyNMJzQHSRvIRog8FnF9AOB3IajxvgQhgSTBD2thHCLwxy6/WlOD689uQd+l1BXs+pw2EWRmIAwbn1t6cX45duF4IqF0qmBfFB46P9i9VwXlJ+cNdkm/HpP/8tG2ela4sb5iwdablwPOQvFtC3xezLd5+BGpEcgU31OY4Le7sC8eXvKwoU1eUP7fnz5MRXsLobIL+hNLFk5N/3tayiqrRTnHvbGQ1eJwDqAtSrna26wv0oI7fFVY+vYcbcxX0SBYwkGS9LQpUftudRpoD1xm7/VgiFVK3be3MrBkGMF5CxwmJH5RAxXG4ECdPiDvQNKKcbrptp+9LLwOJIFBInRarpsk9RSnDPy4YJZUGA210jJNtkx/N6ra5HBh4CAyXrfKaLZJCkwbDr6VkHo6q3YL+deqakEBcy/MU300446Fi/ttDnPR1Uf6sl6Sed5nxPL7GB+f1CeosYD0igzzpFzWmI2ClajeoeciNvfo2dUlGGxZyXBaMujtniW4ijhVLK7I+XLBky3i07/lXLdNv1t0HbOyNEow2Q=
