# Generated by Django 3.0.2 on 2020-01-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500)),
                ('query_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
    ]
